project_name: pgcenter
before:
  hooks:
  - make dep
  - make clean
builds:
  -
    id: "default"
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/lesovsky/pgcenter/cmd.gitTag={{.Tag}}
      - -X github.com/lesovsky/pgcenter/cmd.gitCommit={{.ShortCommit}}
      - -X github.com/lesovsky/pgcenter/cmd.gitBranch=master
nfpms:
  -
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
      linux: Linux
    homepage: https://pgcenter.org
    maintainer: Alexey Lesovsky <lesovsky@gmail.com>
    description: Command-line admin tool for observing and troubleshooting Postgres.
    license: BSD-3
    formats:
      - deb
      - rpm
    bindir: /usr/bin
archives:
  - id: default
    replacements:
      amd64: x86_64
      linux: Linux
    files:
      - COPYRIGHT
      - README.md
      - doc/*
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - typo
